version: '3.8'
services:
  books-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.debug
    container_name: books-api
    environment:
      PORT: 3000
    command: node_modules/.bin/ts-node-dev --poll --exit-child --debug --respawn --inspect=0.0.0.0:9229 src/server.ts
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/app/src